### PR TITLE
Create PatchMyPC-Remove-JRE8.ps1

### PR DESCRIPTION
**Pull request by smcallister594**
## Pull Request Type

- [X] New Script
- [ ] Edit Script
- [ ] Repository Improvement

## Brief summary of changes

The need for this came from a support call with a Customer where the recommended pre-script for Java didn't function properly, letting their devices up date while leaving previous versions installed. 

The customer now has a need to remove all previous versions of Java from all devices which are already up to date. The proposed solutions were 

- Wait for the next release of Java to resolve the issue
- Deploy the app with custom detection logic to allow it to run on devices that are already up to date and pass the REMOVEOUTODATAJRES=1 parameter
- Deploy the recommended pre-script to remove all JREs from all devices and then redeploy the required one
- Deploy a custom script to remove specific versions, leaving only the required one (hence this script)

This is a modification of Andrews script to remove previous JRE8 versions to allow a specific version to be retained 
e.g.
    .\PatchMyPC-Remove-JRE8.ps1 -VersionToExclude "361 (64-bit)"
    This will remove all versions of JRE8 except 8u361 x64
e.g.
    .\PatchMyPC-Remove-JRE8.ps1 -VersionToExclude "361"
    This will remove all versions of JRE8 except 8u361 x86 and x64

## Describe your Testing

I installed around 12 versions of of Java, tested the 2 scenarios listed above in the description and all I'm left with is 1 version
image

## Checklist

- [X] Did you Clean your script - No environment details, comments are PG-13
- [X] Did you test your script
- [X] If required, did you create, and include a Read Me as outlined in [Community Scripts Read Me](README.MD)

## Notes for PMPC Team

Include any other generic notes for the PMPC review team here.

### CODE REVIEW

**Comment by smcallister594** [comment]
@PatchMyPCTeam/pmpc-community-script-maintainers  could you review and code-sign please?

**Comment by codaamok** [comment]
Glad to hear my suggestions were thought provoking and provided insight.

> - Wait for the next release of Java to resolve the issue
> - Deploy the app with custom detection logic to allow it to run on devices that are already up to date and pass the REMOVEOUTODATAJRES=1 parameter
> - Deploy the recommended pre-script to remove all JREs from all devices and then redeploy the required one
> - Deploy a custom script to remove specific versions, leaving only the required one (hence this script)

What happens if the customer leaves the script attached and a new version is released?

**Comment by smcallister594** [comment]
They did! I passed them all to the customer, and they refused them all :( 

Assuming you mean the recommended pre-script, it runs as expected when ran manually so I don't know why it failed, there was no log generated. So I don't know what will happen if they just leave it be and wait for 8u371 to be released, but the weren't willing to do that either :(

**Comment by codaamok** [comment]
That's not what I meant, but first help me understand: how do you envisage or recommend this script's usage? As a pre-script on a package or kicked out independently? If the former, that's more the thought process I had; what would happen if the script was still attached to the Publisher through newer versions.

It's a leading question because the answer right now, it looks like the script would uninstall everything except what's in the parameter `-VersionToExclude`. This might be undesirable if a newer version is installed but it leaves behind a stale older versions because of the lingering script.

It's a leading script because I'm trying to tickle the idea where it has logic of "uninstall everything, except the latest, if there's multiple". But this is food for thought

**Comment by smcallister594** [comment]
Ah, I understand. 

Based on the customer's request, their preferred solution was to deploy a script through ConfigMgr that removed everything except for the latest, which they just wanted as 361x64. Still, I figured giving the option to specify was more helpful. 

It'd be a single-use script; I wouldn't expect it to remain in use past removing anything older than 361x64 now then relying on the install param of REMOVEOUTOFDATEJRES=1 and the default recommended pre-script going forward

**Comment by codaamok** [comment]
Cool, makes sense, then yeah this makes perfect sense. It makes me realise it would be good if `Uninstall-Software.ps1` had an `-Exclude` parameter, then that would have worked, too

**Review by codaamok — APPROVED** [review]

**Comment by smcallister594** [comment]
Thanks Adam 😊 @CodyMathis123 can you resign please?

**Review by CodyMathis123 — APPROVED** [review]
Signed and approved

**Pull request merged**
