### PR TITLE
Update ReadMe.md

### PR DESCRIPTION
**Pull request by byteben**
## Pull Request Type

- [x] Edit Script

## Brief summary of changes

Added more info to readme.md

### CODE REVIEW

**Review by CodyMathis123 — APPROVED** [review]
Approved

**Review by CodyMathis123 — APPROVED** [review]
approved

**Comment by byteben** [comment]
Thanks, not sure why Jake doesnt have the option to approve this too

**Review by jshackelford9375 — COMMENTED** [review]
LGTM

**Pull request merged**
