### PR TITLE
Added Remove-ChromeShortcut.ps1

### PR DESCRIPTION
**Pull request by smcallister594**
Added Remove-ChromeShortcut.ps1 and readme

## Pull Request Type

- [X] New Script
- [ ] Edit Script
- [ ] Repository Improvement

## Brief summary of changes

Added Remove-ChromeShortcut.ps1 for customers to use a post-install script for Google Chrome to counter the fact that Chrome creates a desktop shortcut on launch. 

## Describe your Testing

Tested this in my home lab, and script is in production for Scappman already with no issues. 

## Checklist

- [X] Did you Clean your script - No environment details, comments are PG-13
- [X] Did you test your script
- [X] If required, did you create, and include a Read Me as outlined in [Community Scripts Read Me](README.MD)

### CODE REVIEW

**Comment by smcallister594** [comment]
@PatchMyPCTeam/pmpc-community-script-maintainers would 1 of you kind people review this please :)

**Comment by smcallister594** [comment]
Oh, and maybe sign it?

**Review by CodyMathis123 — APPROVED** [review]

**Comment by smcallister594** [comment]
Added in -ErrorAction's @codaamok, I figure either or remove the try/catch 🤷🏻 unless you have a better idea?

**Comment by smcallister594** [comment]
Changed from -ErrorAction STOP to $ErrorActionPreference = 'Stop'

@CodyMathis123  can you resign please?

**Comment by codaamok** [comment]
Removing the try/catch would give you a different experience to what you have now; it would throw a terminating error and return a non-zero exit code. 

Keeping the try/catch with error action preference set to 'stop', is in effect the same thing as using `$ErrorActionPreference = 'SilentlyContinue'`

**Comment by smcallister594** [comment]
Ah ok should I just bin the try/catch then?

**Comment by codaamok** [comment]
This would be a post script, right? If so it doesn't matter, script runner ignores post script exit codes

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by smcallister594** [comment]
Yeah @codaamok  just a post script

**Review by jshackelford9375 — APPROVED** [review]
LGTM

**Pull request merged**
